package cn.mask.mask.label.label.po;

import java.util.Date;

public class LabelPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.id
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.label_category_id
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    private Integer labelCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.label_name
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    private String labelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.owner_id
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.create_time
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.open_time
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    private Date openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column label.open
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    private Boolean open;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.id
     *
     * @return the value of label.id
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.id
     *
     * @param id the value for label.id
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.label_category_id
     *
     * @return the value of label.label_category_id
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public Integer getLabelCategoryId() {
        return labelCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.label_category_id
     *
     * @param labelCategoryId the value for label.label_category_id
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public void setLabelCategoryId(Integer labelCategoryId) {
        this.labelCategoryId = labelCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.label_name
     *
     * @return the value of label.label_name
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.label_name
     *
     * @param labelName the value for label.label_name
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.owner_id
     *
     * @return the value of label.owner_id
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.owner_id
     *
     * @param ownerId the value for label.owner_id
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.create_time
     *
     * @return the value of label.create_time
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.create_time
     *
     * @param createTime the value for label.create_time
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.open_time
     *
     * @return the value of label.open_time
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.open_time
     *
     * @param openTime the value for label.open_time
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column label.open
     *
     * @return the value of label.open
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public Boolean getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column label.open
     *
     * @param open the value for label.open
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    public void setOpen(Boolean open) {
        this.open = open;
    }
}