package cn.mask.mask.label.label.dao;

import cn.mask.mask.label.label.po.LabelPO;

public interface LabelPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    int insert(LabelPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    int insertSelective(LabelPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    LabelPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    int updateByPrimaryKeySelective(LabelPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table label
     *
     * @mbg.generated Fri Apr 01 14:07:12 CST 2022
     */
    int updateByPrimaryKey(LabelPO record);
}